name = "rearrayfx"
version = "0.1.0"
license = "BSD-2-Clause-Patent"
author = "Bálint Aradi"
maintainer = "aradi@uni-bremen.de"
copyright = "Copyright 2023, Bálint Aradi"
[build]
auto-executables = true
auto-tests = false
auto-examples = false
module-naming = false
[install]
library = false
[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"
